apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-servicemonitor
  # must by the same namespace that Prometheus is running in
  namespace: monitoring
  labels:
    app: detector-placa-veiculos-model
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: detector-placa-veiculos-model
  endpoints:
    - path: metrics
      port: detector-placa-veiculos-rest
      interval: 15s
  namespaceSelector:
    any: true