services:
  detector_placa_veiculos:
    image: tensorflow/serving:latest
    volumes:
      - ./models:/models
      - ./models/detector_placa_veiculos:/models/detector_placa_veiculos
    command: --model_config_file=/models/models.config \
    --model_config_file_poll_wait_seconds=60 \
    --allow_version_labels_for_unavailable_models=true
    ports:
      - "8501:8501"
    links:
      - detector_placa_veiculos_api
      - locust
  detector_placa_veiculos_api:
    image: detector_placa_veiculos_api
    ports:
      - "80:80"
    links:
      - locust
  locust:
    image: locustio/locust:tensorflow
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py
