apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
  labels:
    app: detector-placa-veiculos-api
spec:
  selector:
    app: detector-placa-veiculos-api
  ports:
    - name: detector-placa-veiculos-api-rest
      port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort
